name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} /bin/bash << 'EOF'
          set -e
          export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          REPO_DIR="$HOME/projects/TwiLive-bot"

          mkdir -p "$REPO_DIR"
          cd "$REPO_DIR"

          if [ ! -d .git ]; then
            git clone --branch main --single-branch https://github.com/HarkushaVlad/TwiLive-bot.git .
          else
            git fetch origin main
            git reset --hard origin/main
            git clean -fd 
          fi

          cat > .env <<EOL
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}
          TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }}
          STREAMER_USERNAME=${{ secrets.STREAMER_USERNAME }}
          SEGMENT_DURATION=${{ secrets.SEGMENT_DURATION }}
          FPS=${{ secrets.FPS }}
          SCALE_WIDTH=${{ secrets.SCALE_WIDTH }}
          POSTGRES_URL=${{ secrets.POSTGRES_URL }}
          POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          EOL
          
          docker-compose down --remove-orphans
          docker-compose up -d --build
          EOF
